import type { FoodItem, MealGoals, FoodGroup } from './types';
import {
    RiceVisual, DalVisual, SabziVisual, RaitaVisual, RotiVisual, PaneerVisual,
    ChickenCurryVisual, SaladVisual, ButterChickenVisual, ParathaVisual, CholeVisual,
    BhindiSabziVisual, YogurtVisual, BrownRiceVisual, RedRiceVisual, BeanCurryVisual,
    FriedFishVisual, PappadumVisual, MasalaDosaVisual, ChanaMasalaVisual, PalakDalVisual,
    MasoorDalVisual, MoongDalTadkaVisual, RajmaMasalaVisual, SambarVisual, BainganBhartaVisual,
    BhindiMasalaVisual, PalakPaneerVisual, MixedVegCurryVisual, MethiTheplaVisual,
    MoongDalCheelaVisual, PohaVisual, JowarRotiVisual, SproutsSaladVisual, LemonRiceVisual,
    MoongDalSoupVisual, TomatoSoupVisual, CucumberRaitaVisual, CorianderChutneyVisual,
    CookedBeansVisual, GarlicNaanVisual, CheeseNaanVisual, SamosaVisual,
    ChickpeaCurryVisual, Chicken65Visual, NaanVisual, LadduVisual, MurukkuVisual, JalebiVisual, BombayMixVisual, PuttuVisual, VadaVisual, PaniPuriVisual, UpmaVisual,
    AlooGobiVisual, DalMakhaniVisual, VegBiryaniVisual
} from './components/FoodVisuals';


export const FOOD_DATA: FoodItem[] = [
    // Grains
    {
        id: 'rice_white',
        label: 'White Rice',
        category: 'Grains',
        visual: RiceVisual,
        density_g_per_ml: 0.85,
        volume_options_ml: [80, 120, 160, 240, 360],
        volume_labels: ['Small Katori', 'Katori', 'Scoop', 'Large Scoop', 'Heaping'],
        nutrients_per_100g: { calories_kcal: 130, protein_g: 2.7, carbs_g: 28, fiber_g: 0.4, fat_g: 0.3, sodium_mg: 1 },
    },
    {
        id: 'rice_brown',
        label: 'Brown Rice',
        category: 'Grains',
        visual: BrownRiceVisual,
        density_g_per_ml: 0.8,
        volume_options_ml: [80, 120, 160, 240, 360],
        volume_labels: ['Small Katori', 'Katori', 'Scoop', 'Large Scoop', 'Heaping'],
        nutrients_per_100g: { calories_kcal: 111, protein_g: 2.6, carbs_g: 23, fiber_g: 1.8, fat_g: 0.9, sodium_mg: 5 },
    },
    {
        id: 'rice_red',
        label: 'Red Rice',
        category: 'Grains',
        visual: RedRiceVisual,
        density_g_per_ml: 0.82,
        volume_options_ml: [80, 120, 160, 240, 360],
        volume_labels: ['Small Katori', 'Katori', 'Scoop', 'Large Scoop', 'Heaping'],
        nutrients_per_100g: { calories_kcal: 125, protein_g: 3.0, carbs_g: 26, fiber_g: 2.2, fat_g: 1.0, sodium_mg: 3 },
    },
     {
        id: 'lemon_rice',
        label: 'Lemon Rice',
        category: 'Grains',
        visual: LemonRiceVisual,
        density_g_per_ml: 0.85,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 160, protein_g: 3, carbs_g: 30, fiber_g: 1, fat_g: 3, sodium_mg: 200 },
    },
    {
        id: 'veg_biryani',
        label: 'Veg Biryani',
        category: 'Grains',
        visual: VegBiryaniVisual,
        density_g_per_ml: 0.8,
        volume_options_ml: [150, 250, 350],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 180, protein_g: 4, carbs_g: 30, fiber_g: 3, fat_g: 5, sodium_mg: 300 },
    },
    // Lentils & Curries
    {
        id: 'dal_tadka',
        label: 'Dal Tadka',
        category: 'Lentils & Curries',
        visual: DalVisual,
        density_g_per_ml: 1.05,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 115, protein_g: 6, carbs_g: 15, fiber_g: 5, fat_g: 3.5, sodium_mg: 250 },
    },
    {
        id: 'chana_masala',
        label: 'Chana Masala',
        category: 'Lentils & Curries',
        visual: ChanaMasalaVisual,
        density_g_per_ml: 1.1,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 135, protein_g: 6, carbs_g: 18, fiber_g: 7, fat_g: 4, sodium_mg: 280 },
    },
     {
        id: 'chickpea_curry',
        label: 'Chickpea Curry',
        category: 'Lentils & Curries',
        visual: ChickpeaCurryVisual,
        density_g_per_ml: 1.1,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 145, protein_g: 7, carbs_g: 20, fiber_g: 8, fat_g: 4.5, sodium_mg: 300 },
    },
    {
        id: 'palak_dal',
        label: 'Palak Dal',
        category: 'Lentils & Curries',
        visual: PalakDalVisual,
        density_g_per_ml: 1.05,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 110, protein_g: 7, carbs_g: 12, fiber_g: 6, fat_g: 3, sodium_mg: 220 },
    },
    {
        id: 'masoor_dal',
        label: 'Masoor Dal',
        category: 'Lentils & Curries',
        visual: MasoorDalVisual,
        density_g_per_ml: 1.05,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 120, protein_g: 8, carbs_g: 16, fiber_g: 5, fat_g: 2.5, sodium_mg: 240 },
    },
    {
        id: 'moong_dal_tadka',
        label: 'Moong Dal Tadka',
        category: 'Lentils & Curries',
        visual: MoongDalTadkaVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 105, protein_g: 7, carbs_g: 14, fiber_g: 4, fat_g: 2, sodium_mg: 230 },
    },
    {
        id: 'rajma_masala',
        label: 'Rajma Masala',
        category: 'Lentils & Curries',
        visual: RajmaMasalaVisual,
        density_g_per_ml: 1.1,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 140, protein_g: 8, carbs_g: 18, fiber_g: 7, fat_g: 3, sodium_mg: 280 },
    },
    {
        id: 'sambar',
        label: 'Sambar',
        category: 'Lentils & Curries',
        visual: SambarVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 90, protein_g: 4, carbs_g: 12, fiber_g: 5, fat_g: 2.5, sodium_mg: 260 },
    },
    {
        id: 'paneer_butter_masala',
        label: 'Paneer Butter Masala',
        category: 'Lentils & Curries',
        visual: PaneerVisual,
        density_g_per_ml: 1.1,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 180, protein_g: 8, carbs_g: 9, fiber_g: 2, fat_g: 12, sodium_mg: 350 },
    },
    {
        id: 'chicken_curry',
        label: 'Chicken Curry',
        category: 'Lentils & Curries',
        visual: ChickenCurryVisual,
        density_g_per_ml: 1.1,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 160, protein_g: 15, carbs_g: 6, fiber_g: 1.5, fat_g: 8, sodium_mg: 380 },
    },
    // Vegetable Dishes
    {
        id: 'mixed_sabzi',
        label: 'Mixed Sabzi',
        category: 'Vegetable Dishes',
        visual: SabziVisual,
        density_g_per_ml: 0.9,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 80, protein_g: 2, carbs_g: 10, fiber_g: 4, fat_g: 3, sodium_mg: 180 },
    },
    {
        id: 'aloo_gobi',
        label: 'Aloo Gobi',
        category: 'Vegetable Dishes',
        visual: AlooGobiVisual,
        density_g_per_ml: 0.85,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 90, protein_g: 2.5, carbs_g: 12, fiber_g: 3.5, fat_g: 4, sodium_mg: 220 },
    },
    {
        id: 'baingan_bharta',
        label: 'Baingan Bharta',
        category: 'Vegetable Dishes',
        visual: BainganBhartaVisual,
        density_g_per_ml: 0.95,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 75, protein_g: 2, carbs_g: 8, fiber_g: 4, fat_g: 4, sodium_mg: 200 },
    },
    {
        id: 'bhindi_masala',
        label: 'Bhindi Masala',
        category: 'Vegetable Dishes',
        visual: BhindiMasalaVisual,
        density_g_per_ml: 0.8,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 95, protein_g: 2.5, carbs_g: 8, fiber_g: 3.5, fat_g: 5, sodium_mg: 220 },
    },
    {
        id: 'palak_paneer',
        label: 'Palak Paneer',
        category: 'Vegetable Dishes',
        visual: PalakPaneerVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 140, protein_g: 10, carbs_g: 6, fiber_g: 3, fat_g: 9, sodium_mg: 300 },
    },
    {
        id: 'mixed_veg_curry',
        label: 'Mixed Veg Curry',
        category: 'Vegetable Dishes',
        visual: MixedVegCurryVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 100, protein_g: 3, carbs_g: 12, fiber_g: 5, fat_g: 4.5, sodium_mg: 250 },
    },
    {
        id: 'beans_cooked_side',
        label: 'Cooked Beans',
        category: 'Vegetable Dishes',
        visual: CookedBeansVisual,
        density_g_per_ml: 0.9,
        volume_options_ml: [80, 120, 160],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 130, protein_g: 8, carbs_g: 24, fiber_g: 7, fat_g: 0.5, sodium_mg: 200 },
    },
    // Breads & Breakfast
    {
        id: 'roti',
        label: 'Roti',
        category: 'Breads & Breakfast',
        visual: RotiVisual,
        portion_g: [30, 60, 90],
        portion_labels: ['1 piece', '2 pieces', '3 pieces'],
        nutrients_per_100g: { calories_kcal: 297, protein_g: 11, carbs_g: 61, fiber_g: 7, fat_g: 2, sodium_mg: 450 },
    },
     {
        id: 'naan_plain',
        label: 'Plain Naan',
        category: 'Breads & Breakfast',
        visual: NaanVisual,
        portion_g: [70, 140],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 310, protein_g: 10, carbs_g: 52, fiber_g: 2, fat_g: 7, sodium_mg: 450 },
    },
    {
        id: 'methi_thepla',
        label: 'Methi Thepla',
        category: 'Breads & Breakfast',
        visual: MethiTheplaVisual,
        portion_g: [35, 70],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 320, protein_g: 10, carbs_g: 55, fiber_g: 8, fat_g: 6, sodium_mg: 480 },
    },
    {
        id: 'moong_dal_cheela',
        label: 'Moong Dal Cheela',
        category: 'Breads & Breakfast',
        visual: MoongDalCheelaVisual,
        portion_g: [60, 120],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 180, protein_g: 10, carbs_g: 25, fiber_g: 4, fat_g: 4, sodium_mg: 150 },
    },
     {
        id: 'poha',
        label: 'Poha',
        category: 'Breads & Breakfast',
        visual: PohaVisual,
        density_g_per_ml: 0.4,
        volume_options_ml: [150, 250, 350],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 110, protein_g: 2, carbs_g: 24, fiber_g: 1, fat_g: 1, sodium_mg: 180 },
    },
    {
        id: 'jowar_roti',
        label: 'Jowar Roti',
        category: 'Breads & Breakfast',
        visual: JowarRotiVisual,
        portion_g: [40, 80],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 330, protein_g: 10, carbs_g: 70, fiber_g: 9, fat_g: 1.5, sodium_mg: 20 },
    },
    {
        id: 'puttu',
        label: 'Puttu',
        category: 'Breads & Breakfast',
        visual: PuttuVisual,
        portion_g: [100, 200],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 190, protein_g: 3, carbs_g: 40, fiber_g: 2.5, fat_g: 2, sodium_mg: 10 },
    },
    {
        id: 'upma',
        label: 'Upma',
        category: 'Breads & Breakfast',
        visual: UpmaVisual,
        density_g_per_ml: 0.7,
        volume_options_ml: [150, 250, 350],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 150, protein_g: 4, carbs_g: 28, fiber_g: 2, fat_g: 2.5, sodium_mg: 300 },
    },
    // Soups, Salads & Sides
    {
        id: 'sprouts_salad',
        label: 'Sprouts Salad',
        category: 'Soups, Salads & Sides',
        visual: SproutsSaladVisual,
        density_g_per_ml: 0.5,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 95, protein_g: 7, carbs_g: 15, fiber_g: 5, fat_g: 1, sodium_mg: 50 },
    },
    {
        id: 'moong_dal_soup',
        label: 'Moong Dal Soup',
        category: 'Soups, Salads & Sides',
        visual: MoongDalSoupVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [150, 250],
        volume_labels: ['Small', 'Large'],
        nutrients_per_100g: { calories_kcal: 70, protein_g: 4, carbs_g: 10, fiber_g: 3, fat_g: 1.5, sodium_mg: 180 },
    },
    {
        id: 'tomato_soup',
        label: 'Tomato Soup',
        category: 'Soups, Salads & Sides',
        visual: TomatoSoupVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [150, 250],
        volume_labels: ['Small', 'Large'],
        nutrients_per_100g: { calories_kcal: 60, protein_g: 1.5, carbs_g: 12, fiber_g: 2, fat_g: 0.5, sodium_mg: 250 },
    },
    {
        id: 'cucumber_raita',
        label: 'Cucumber Raita',
        category: 'Soups, Salads & Sides',
        visual: CucumberRaitaVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [80, 120],
        volume_labels: ['Small', 'Regular'],
        nutrients_per_100g: { calories_kcal: 60, protein_g: 3, carbs_g: 4, fiber_g: 0.5, fat_g: 3.5, sodium_mg: 150 },
    },
    {
        id: 'coriander_chutney',
        label: 'Coriander Chutney',
        category: 'Soups, Salads & Sides',
        visual: CorianderChutneyVisual,
        density_g_per_ml: 1.1,
        volume_options_ml: [30, 60],
        volume_labels: ['Serving', 'Double'],
        nutrients_per_100g: { calories_kcal: 40, protein_g: 1, carbs_g: 8, fiber_g: 2, fat_g: 0.5, sodium_mg: 300 },
    },
    {
        id: 'salad',
        label: 'Salad',
        category: 'Soups, Salads & Sides',
        visual: SaladVisual,
        density_g_per_ml: 0.3,
        volume_options_ml: [150, 250],
        volume_labels: ['Side', 'Large'],
        nutrients_per_100g: { calories_kcal: 30, protein_g: 1, carbs_g: 5, fiber_g: 2, fat_g: 0.5, sodium_mg: 20 },
    },
    {
        id: 'yogurt',
        label: 'Plain Yogurt',
        category: 'Soups, Salads & Sides',
        visual: YogurtVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [100, 150],
        volume_labels: ['Small', 'Regular'],
        nutrients_per_100g: { calories_kcal: 59, protein_g: 10, carbs_g: 3.6, fiber_g: 0, fat_g: 0.4, sodium_mg: 36 },
    },
    // Treats
    {
        id: 'dal_makhani',
        label: 'Dal Makhani',
        category: 'Treats',
        visual: DalMakhaniVisual,
        density_g_per_ml: 1.1,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 160, protein_g: 7, carbs_g: 15, fiber_g: 6, fat_g: 8, sodium_mg: 350 },
        isTreat: true,
    },
    {
        id: 'garlic_naan',
        label: 'Garlic Naan',
        category: 'Treats',
        visual: GarlicNaanVisual,
        portion_g: [80, 160],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 320, protein_g: 9, carbs_g: 50, fiber_g: 3, fat_g: 9, sodium_mg: 600 },
        isTreat: true,
    },
    {
        id: 'cheese_naan',
        label: 'Cheese Naan',
        category: 'Treats',
        visual: CheeseNaanVisual,
        portion_g: [90, 180],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 350, protein_g: 12, carbs_g: 48, fiber_g: 2.5, fat_g: 13, sodium_mg: 700 },
        isTreat: true,
    },
    {
        id: 'samosa',
        label: 'Samosa',
        category: 'Treats',
        visual: SamosaVisual,
        portion_g: [80, 160],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 262, protein_g: 4, carbs_g: 24, fiber_g: 2, fat_g: 17, sodium_mg: 420 },
        isTreat: true,
    },
    {
        id: 'chicken_65',
        label: 'Chicken 65',
        category: 'Treats',
        visual: Chicken65Visual,
        density_g_per_ml: 0.7,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 280, protein_g: 18, carbs_g: 15, fiber_g: 1, fat_g: 16, sodium_mg: 650 },
        isTreat: true,
    },
    {
        id: 'paratha',
        label: 'Paratha',
        category: 'Treats',
        visual: ParathaVisual,
        portion_g: [50, 100],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 350, protein_g: 8, carbs_g: 45, fiber_g: 5, fat_g: 15, sodium_mg: 500 },
        isTreat: true,
    },
    {
        id: 'butter_chicken',
        label: 'Butter Chicken',
        category: 'Treats',
        visual: ButterChickenVisual,
        density_g_per_ml: 1.12,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 220, protein_g: 16, carbs_g: 8, fiber_g: 1, fat_g: 15, sodium_mg: 400 },
        isTreat: true,
    },
    {
        id: 'fried_fish',
        label: 'Fried Fish Curry',
        category: 'Treats',
        visual: FriedFishVisual,
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Small', 'Medium', 'Large'],
        nutrients_per_100g: { calories_kcal: 190, protein_g: 18, carbs_g: 5, fiber_g: 1, fat_g: 11, sodium_mg: 320 },
        isTreat: true,
    },
    {
        id: 'pappadum',
        label: 'Pappadum',
        category: 'Treats',
        visual: PappadumVisual,
        portion_g: [12, 24],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 450, protein_g: 20, carbs_g: 60, fiber_g: 2, fat_g: 15, sodium_mg: 1200 },
        isTreat: true,
    },
    {
        id: 'masala_dosa',
        label: 'Masala Dosa',
        category: 'Treats',
        visual: MasalaDosaVisual,
        portion_g: [250],
        portion_labels: ['1 Dosa'],
        nutrients_per_100g: { calories_kcal: 160, protein_g: 4, carbs_g: 25, fiber_g: 3, fat_g: 5, sodium_mg: 450 },
        isTreat: true,
    },
    {
        id: 'laddu',
        label: 'Laddu',
        category: 'Treats',
        visual: LadduVisual,
        portion_g: [30, 60],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 400, protein_g: 6, carbs_g: 60, fiber_g: 2, fat_g: 16, sodium_mg: 50 },
        isTreat: true,
    },
    {
        id: 'murukku',
        label: 'Murukku',
        category: 'Treats',
        visual: MurukkuVisual,
        portion_g: [25, 50],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 500, protein_g: 8, carbs_g: 55, fiber_g: 4, fat_g: 28, sodium_mg: 800 },
        isTreat: true,
    },
    {
        id: 'jalebi',
        label: 'Jalebi',
        category: 'Treats',
        visual: JalebiVisual,
        portion_g: [40, 80],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 450, protein_g: 4, carbs_g: 75, fiber_g: 1, fat_g: 15, sodium_mg: 20 },
        isTreat: true,
    },
    {
        id: 'bombay_mix',
        label: 'Bombay Mix',
        category: 'Treats',
        visual: BombayMixVisual,
        density_g_per_ml: 0.4,
        volume_options_ml: [60, 120],
        volume_labels: ['Handful', 'Large Handful'],
        nutrients_per_100g: { calories_kcal: 520, protein_g: 14, carbs_g: 45, fiber_g: 8, fat_g: 30, sodium_mg: 900 },
        isTreat: true,
    },
    {
        id: 'vada',
        label: 'Vada',
        category: 'Treats',
        visual: VadaVisual,
        portion_g: [50, 100],
        portion_labels: ['1 piece', '2 pieces'],
        nutrients_per_100g: { calories_kcal: 330, protein_g: 12, carbs_g: 30, fiber_g: 5, fat_g: 18, sodium_mg: 550 },
        isTreat: true,
    },
    {
        id: 'pani_puri',
        label: 'Pani Puri',
        category: 'Treats',
        visual: PaniPuriVisual,
        portion_g: [120, 240],
        portion_labels: ['4 pieces', '8 pieces'],
        nutrients_per_100g: { calories_kcal: 280, protein_g: 8, carbs_g: 45, fiber_g: 5, fat_g: 8, sodium_mg: 700 },
        isTreat: true,
    },
];


export const FOOD_GROUPS: FoodGroup[] = [
    {
        name: 'Grains',
        items: FOOD_DATA.filter(item => item.category === 'Grains')
    },
    {
        name: 'Lentils & Curries',
        items: FOOD_DATA.filter(item => item.category === 'Lentils & Curries')
    },
    {
        name: 'Vegetable Dishes',
        items: FOOD_DATA.filter(item => item.category === 'Vegetable Dishes')
    },
    {
        name: 'Breads & Breakfast',
        items: FOOD_DATA.filter(item => item.category === 'Breads & Breakfast')
    },
    {
        name: 'Soups, Salads & Sides',
        items: FOOD_DATA.filter(item => item.category === 'Soups, Salads & Sides')
    },
    {
        name: 'Treats',
        items: FOOD_DATA.filter(item => item.category === 'Treats')
    }
];


type MealGoalConfig = Omit<MealGoals, 'carbs_g' | 'protein_g' | 'fat_g'>;

export const MEAL_GOALS: Record<'Light' | 'Regular' | 'Hearty', MealGoalConfig> = {
    Light: {
        calories_kcal: { min: 400, max: 500, target: 450 },
        fiber_g: { min: 8 },
        sodium_mg: { max: 600 },
    },
    Regular: {
        calories_kcal: { min: 540, max: 660, target: 600 },
        fiber_g: { min: 10 },
        sodium_mg: { max: 800 },
    },
    Hearty: {
        calories_kcal: { min: 675, max: 825, target: 750 },
        fiber_g: { min: 12 },
        sodium_mg: { max: 1000 },
    },
};